### ISSUE TITLE
Distribution security

### ISSUE THREAD

**Issue by Zero3** [wurstscript/WurstScript#652]
I was about to try WurstScript, but noted two issues with the distribution security: The download button on the frontpage of https://wurstlang.org/ links to http://peeeq.de/hudson/job/WurstSetup/lastSuccessfulBuild/artifact/downloads/WurstSetup.jar. The issues are:

1) The .jar file is served over HTTP and not HTTPS.

2) The .jar file is hosted on a completely different domain.

While there probably isn't anything malicious about the .jar, I would say that it is quite bad practice to serve executable code like this.

**Comment by Frotty** [comment]
Yes, we are aware of this. The link is actually available as https, but we kept it http because our ssl certificate from Let's encrypt causes some problems in restrictive countries such as china.
But I agree that it should be the default and http fallback.

**Comment by Frotty** [comment]
Addressed via 13b99a042a765c4b36664503a828ae7716f24767

If you have further suggestions please open issues on the website's repo https://github.com/wurstscript/wurstscript.github.io

**Comment by Zero3** [comment]
@Frotty :+1:

Apologies for not opening this issue in the wrong repository.

That change does not fix the issue about serving the file from a completely different domain, though...

**Comment by Frotty** [comment]
As I said above, I don't know of an easy way to solve that.
We can't add it to the page directly, since it's a github pages repo.
The only possibility I see would be github releases, but they are annoying to set up, and I didn't find a easy "download last release" direct link.
If you have more insight on this, please do share.

**Comment by peq** [comment]
We could maybe have a subdomain like we have for the [pastebin](https://bin.wurstlang.org/).

**Comment by Zero3** [comment]
@peq Nice change with the subdomain. It looks much more trustworthy now!

I download binaries from GitHub release pages all the time, so I don't know what you mean with not being able to do so.
